Feat: milestone api 구현
boostcamp-2020/IssueTracker-25 pull request #114
Opened 2020-11-08 18:24 UTC by LeeSuKyeong

서버 디렉토리 부분에서 모든 milestone data를 읽어오는 api를 구현했습니다.

2020-11-09 00:38 UTC, rolled-potatoes requested changes

2020-11-09 00:38 UTC, rolled-potatoes commented on server/src/services/milestone.js
> +    return MilestoneModel.findAll();
진행 퍼센트 표시랑 몇개 열리고 닫히고 표시하려면
마일스톤을 가져올 때 관련 포함된 이슈도 가져와야 할 것 같아요 !
![스크린샷 2020-11-09 오전 9 33 08](https://user-images.githubusercontent.com/44409642/98488812-98309600-226e-11eb-90d5-7e515a644ef9.png)

2020-11-09 03:58 UTC, changheedev commented on server/src/services/milestone.js
> +    return MilestoneModel.findAll();
마일스톤을 불러올때 관련된 이슈를 함께 불러오는 것하고 open/close 상태의 각 count 값만 같이 넘겨주는 방식도 있을 것 같은데 어떤 방식으로 할지 의논해보면 좋을 것 같습니다.

2020-11-10 15:02 UTC, changheedev approved these changes

2020-11-10 15:02 UTC, changheedev commented on server/src/services/milestone.js
> +    return `(
오 드디어 최종본인가요 ?! 굳굳 👍 
뭐 큰 의미는 없을 수도 있겠지만 query라는 이름보다는 count 값을 가져오는 query라는 것을 명시할 수 있는 이름으로 사용하면 더 좋을 것 같습니다.

2020-11-10 21:34 UTC, yejineee approved these changes

2020-11-10 21:34 UTC, yejineee commented on server/src/services/milestone.js
> +          [sequelize.literal(query(false)), 'openedCount'],
오 이렇게 raw query 사용하셨네요ㅠㅠ 문제 해결해주시다닛....감동 😭

2020-11-11 01:32 UTC, rolled-potatoes approved these changes

2020-11-11 01:32 UTC, merged